FROM --platform=linux/x86_64 node:18.17.1

ENV NODE_ENV production
ENV PORT 80

RUN mkdir /app
WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

ENTRYPOINT ["npm", "run", "start"]