default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME" ) {  } %>
  username: <%= ENV.fetch("DATABASE_USERNAME"){  } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD"){  } %>
  host:  <%= ENV.fetch("DATABASE_HOST"){  } %>

development:
  <<: *default
  host: mysql_db
  database: db_development
  password: password

test:
  <<: *default
  host: mysql_db
  database: db_test
  password: password