default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306

development:
  <<: *default
  host: mysql_db
  database: db_development
  password: password

test:
  <<: *default
  host: mysql_db
  database: db_test
  password: password