import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/layouts/Header'
import Footer from '../components/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
    <div className="flex flex-col min-h-screen bg-white">
      <Header />
      <main className="flex-grow text-black pt-32 pb-20">
        {children}
      </main>
      <Footer />
    </div>
      </body>
    </html>
  )
}
